=== hanhphucnguyen/passwordmanager/PasswordManager/JsonFile/accInfo-Schema.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"title": "Account Information Schema",
	"type": "object",
	"required": [ "Description", "UserId", "Password" ],
	"additionalProperties": false,
	"properties": {
		"Description": {
			"type": "string",
			"title": "The Description Schema"
		},
		"UserId": {
			"type": "string",
			"title": "The Userid Schema"
		},
		"LoginUrl": {
			"type": "string",
			"title": "The Loginurl Schema",
			"format": "Uri"
		},
		"AccountNum": {
			"type": "string",
			"title": "The Accountnum Schema"
		},
		"Password": {
			"type": "object",
			"title": "The Password Schema",
			"required": [ "Value", "StrengthNum", "StrengthText" ],
			"additionalProperties": false,
			"properties": {
				"Value": {
					"type": "string",
					"title": "The Value Schema"
				},
				"StrengthNum": {
					"type": "number",
					"title": "The Strengthnum Schema",
					"minimum": 0,
					"maximum": 100
				},
				"StrengthText": {
					"type": "string",
					"title": "The Strengthtext Schema",
					"enum": [ "very weak", "weak", "good", "strong", "very strong" ]
				},
				"LastReset": {
					"type": "string",
					"title": "The Lastreset Schema"
				}
			}
		}
	}
}

=== hanhphucnguyen/passwordmanager/myAccInfo.json
[{"Password":{"Value":"vgfgfA1","StrengthNum":71.0,"StrengthText":"strong","LastReset":"2019-05-20"},"Description":"Google account","UserId":"LeoNguyen","LoginUrl":"http://www.google.com","AccountNum":"3567546fg"},{"Password":{"Value":"vgfgfA1","StrengthNum":71.0,"StrengthText":"strong","LastReset":"2019-05-24"},"Description":"Facebook account","UserId":"LeoNguyen","LoginUrl":"http://www.facebook.com","AccountNum":"56657657"},{"Password":{"Value":"98765","StrengthNum":71.0,"StrengthText":"strong","LastReset":"2019-05-12"},"Description":"Spotify account","UserId":"LeoNguyen","LoginUrl":"http://www.google.com","AccountNum":"3567546fg"}]
